### ISSUE TITLE
TypeError: Cannot call method 'hasAudio' of undefined

### ISSUE THREAD

**Issue by peili** [ging/licode#223]
Running Licode HEAD on Ubuntu 14:

2014-12-12 13:44:05.695  - INFO: RoomController - Removing subscriptions of  9JsxDSX1Ycn8h7cLuCBD

/root/licode/erizo_controller/erizoController/erizoController.js:676
                        if (socket.room.streams[id].hasAudio() || socket.room.
                                                    ^
TypeError: Cannot call method 'hasAudio' of undefined
    at Socket.<anonymous> (/root/licode/erizo_controller/erizoController/erizoController.js:676:53)
    at Socket.emit [as $emit] (events.js:95:17)
    at Socket.onDisconnect (/root/licode/node_modules/socket.io/lib/socket.js:153:10)
    at SocketNamespace.handleDisconnect (/root/licode/node_modules/socket.io/lib/namespace.js:229:46)
    at Manager.onClientDisconnect (/root/licode/node_modules/socket.io/lib/manager.js:501:29)
    at WebSocket.Transport.end (/root/licode/node_modules/socket.io/lib/transport.js:467:20)
    at Parser.<anonymous> (/root/licode/node_modules/socket.io/lib/transports/websocket/hybi-16.js:52:10)
    at Parser.emit (events.js:92:17)
    at Parser.opcodeHandlers.8 (/root/licode/node_modules/socket.io/lib/transports/websocket/hybi-16.js:382:12)
    at Parser.processPacket (/root/licode/node_modules/socket.io/lib/transports/websocket/hybi-16.js:533:8)
2014-12-12 13:44:10.060  - INFO: TokensResource - Created token for room  548aae9d9d47a92329aeb203 and service  53466d2868f84217a89381f9
2014-12-12 13:44:12.741  - INFO: TokensResource - Created token for room  548aae9d9d47a92329aeb203 and service  53466d2868f84217a89381f9
2014-12-12 13:44:16.225  - INFO: CloudHandler - ErizoController 1  in  5.9.149.108 does not respond. Deleting it.
2014-12-12 13:44:16.226  - INFO: CloudHandler - [CLOUD HANDLER]: Warning! No erizoController is available.

**Comment by nachoaguadoc** [comment]
Hi all,

This issue has been fixed in the new master branch (old trickle_ice branch)
