### ISSUE TITLE
TypeError in licode/erizo_controller/erizoController/erizoController.js:550

### ISSUE THREAD

**Issue by dmerlitti** [ging/licode#225]
"basic_example" node app running at http://icbsa.cloudapp.net:3001/

Server-side (Ubuntu 12.04.4 LTS):

2014-12-16 12:15:39.560  - INFO: ErizoController - erizoController.js: Starting recorder streamID 530177985783666370url  /tmp/349505375372245900.mkv

/home/azureuser/licode/erizo_controller/erizoController/erizoController.js:550
            if (socket.room.streams[streamId].hasAudio() || socket.room.stream
                                              ^
TypeError: Cannot call method 'hasAudio' of undefined
    at Socket.<anonymous> (/home/azureuser/licode/erizo_controller/erizoController/erizoController.js:550:47)
    at Socket.emit [as $emit] (events.js:98:17)
    at SocketNamespace.handlePacket (/home/azureuser/licode/node_modules/socket.io/lib/namespace.js:335:22)
    at Manager.onClientMessage (/home/azureuser/licode/node_modules/socket.io/lib/manager.js:488:38)
    at WebSocket.Transport.onMessage (/home/azureuser/licode/node_modules/socket.io/lib/transport.js:387:20)
    at Parser.<anonymous> (/home/azureuser/licode/node_modules/socket.io/lib/transports/websocket/hybi-16.js:39:10)
    at Parser.emit (events.js:95:17)
    at finish (/home/azureuser/licode/node_modules/socket.io/lib/transports/websocket/hybi-16.js:288:16)
    at Parser.expectHandler (/home/azureuser/licode/node_modules/socket.io/lib/transports/websocket/hybi-16.js:299:15)
    at Parser.add (/home/azureuser/licode/node_modules/socket.io/lib/transports/websocket/hybi-16.js:466:24)

Client-side (Chrome v. 39.0.2171.71 m):
DEBUG:  Requested access to local media
erizo.js:156 DEBUG:  Object {video: Object, audio: true, fake: undefined, screen: "", extensionId: undefined}
erizo.js:156 INFO:  User has granted access to local media.
erizo.js:156 DEBUG:  Event: access-accepted
erizo.js:140 Object {tokenId: "5490224c4eb82d1bcf737f35", host: "icbsa.cloudapp.net:8080", secure: false, signature: "MTQ0N2E0MmQzMjc3OTRlNjI3YzBmYTFkMjk2MDdlYWVlYTVkMzhiOA=="}
erizo.js:156 DEBUG:  Creating URL from stream [object MediaStream]
erizo.js:166 The 'overflowchanged' event is deprecated and may be removed. Please do not use it.
erizo.js:156 INFO:  Connected to room 549022404eb82d1bcf737f33
erizo.js:156 DEBUG:  Event: room-connected
erizo.js:156 DEBUG:  Stable
erizo.js:156 DEBUG:  Changed v=0
[CUT]
INFO:  Stream published
erizo.js:156 DEBUG:  Start Recording streamaa: 530177985783666370
erizo.js:156 INFO:  Socket disconnected
erizo.js:156 DEBUG:  Event: room-disconnected

**Comment by nachoaguadoc** [comment]
Hi,

This issue has been fixed in the new master branch (old trickle_ice branch)
