### ISSUE TITLE
Nuve Crashes When Deleting A Room

### ISSUE THREAD

**Issue by pybean** [ging/licode#271]
Please check the attached erizo_controller and nuve logs below. My system is from master branch.

Clearly, erizoController tries to remove subscriptions and publisher 'after' rooms[room].roomController is already destroyed. So this causes undefined variable errors. After this error, Nuve dies because it couldn't get the response from erizo_contoller.

We could simply add a condition like 'if (rooms[room].roomComtroller != undefined)' before removing subscriptions or publisher to avoid this error, but I believe refine the deleting process is the best way to do. In addition, Nuve shouldn't die so easily just because it gets a timeout error.

2015-03-17 15:51:17.729  - INFO: RoomController - Adding publisher peer_id  885464985622093000
2015-03-17 15:51:17.730  - INFO: ErizoController - Initializing subscriber
2015-03-17 15:51:17.731  - INFO: RoomController - Using Erizo 9dae087b-73e7-64ab-18e4-37b6d89c711d
2015-03-17 15:51:17.731  - INFO: RoomController - Erizo got
2015-03-17 15:51:21.510  - INFO: ErizoController - Sending message to OO1ifMISOJRU1AxBRL6V in room  5508850fa7138ccd5f0bd9c2
2015-03-17 15:51:21.511  - INFO: ErizoController - Sending message to vBVTSRJ6B_SykBh-RL6W in room  5508850fa7138ccd5f0bd9c2
2015-03-17 15:51:21.513  - INFO: RoomController - Adding subscriber  OO1ifMISOJRU1AxBRL6V  to publisher  885464985622093000
2015-03-17 15:51:21.516  - INFO: ErizoController - Subscriber added
2015-03-17 15:51:21.517  - INFO: ErizoController - Initializing subscriber
2015-03-17 15:52:18.068  - INFO: ErizoController - Sending message to OO1ifMISOJRU1AxBRL6V in room  5508850fa7138ccd5f0bd9c2
2015-03-17 15:52:18.069  - INFO: ErizoController - Sending message to vBVTSRJ6B_SykBh-RL6W in room  5508850fa7138ccd5f0bd9c2
2015-03-17 15:52:18.069  - INFO: RoomController - Removing subscribers 136540154227986930
2015-03-17 15:52:18.070  - INFO: RoomController - Removing publisher 136540154227986930
2015-03-17 15:52:18.070  - INFO: RoomController - Removed all
2015-03-17 15:52:18.070  - INFO: RoomController - Removing muxer 136540154227986930  muxers left  2
2015-03-17 15:52:18.237  - INFO: ErizoController - Sending message to OO1ifMISOJRU1AxBRL6V in room  5508850fa7138ccd5f0bd9c2
2015-03-17 15:52:18.238  - INFO: ErizoController - Sending message to vBVTSRJ6B_SykBh-RL6W in room  5508850fa7138ccd5f0bd9c2
2015-03-17 15:52:18.238  - INFO: RoomController - Removing subscribers 333072711480781440
2015-03-17 15:52:18.238  - INFO: RoomController - Removing publisher 333072711480781440
2015-03-17 15:52:18.239  - INFO: RoomController - Removed all
2015-03-17 15:52:18.239  - INFO: RoomController - Removing muxer 333072711480781440  muxers left  1
2015-03-17 15:52:18.483  - INFO: ErizoController - Socket disconnect  OO1ifMISOJRU1AxBRL6V
2015-03-17 15:52:18.483  - INFO: RoomController - Removing subscriptions of  OO1ifMISOJRU1AxBRL6V
2015-03-17 15:52:18.483  - INFO: RoomController - Removing subscriber  OO1ifMISOJRU1AxBRL6V to muxer  885464985622093000
2015-03-17 15:52:18.514  - INFO: RoomResource - Representing room  5508850fa7138ccd5f0bd9c2 of service  51c3357d0c08cb4b2cbaf775
2015-03-17 15:52:18.519  - INFO: RoomResource - Room  5508850fa7138ccd5f0bd9c2  deleted for service  51c3357d0c08cb4b2cbaf775
2015-03-17 15:52:18.521  - INFO: ErizoController - Deleting room  5508850fa7138ccd5f0bd9c2
2015-03-17 15:52:18.521  - ERROR: AMQPER - Error processing call:  [TypeError: Cannot call method 'removeSubscriptions' of undefined]
TypeError: Cannot call method 'removeSubscriptions' of undefined
    at Object.exports.deleteRoom (/home/pybean/licode/erizo_controller/erizoController/erizoController.js:849:40)
    at Object.exports.deleteRoom (/home/pybean/licode/erizo_controller/erizoController/rpc/rpcPublic.js:19:21)
    at /home/pybean/licode/erizo_controller/common/amqper.js:103:47
    at Message.<anonymous> (/home/pybean/licode/node_modules/amqp/lib/queue.js:190:28)
    at Message.emit (events.js:92:17)
    at Queue._onContent (/home/pybean/licode/node_modules/amqp/lib/queue.js:529:25)
    at AMQPParser.self.parser.onContent (/home/pybean/licode/node_modules/amqp/lib/connection.js:142:32)
    at frameEnd (/home/pybean/licode/node_modules/amqp/lib/parser.js:100:18)
    at frame (/home/pybean/licode/node_modules/amqp/lib/parser.js:78:14)
    at header (/home/pybean/licode/node_modules/amqp/lib/parser.js:64:14)
    at frameEnd (/home/pybean/licode/node_modules/amqp/lib/parser.js:111:16)
2015-03-17 15:52:18.533  - INFO: ErizoController - Sending message to vBVTSRJ6B_SykBh-RL6W in room  5508850fa7138ccd5f0bd9c2
2015-03-17 15:52:18.534  - INFO: RoomController - Removing subscribers 885464985622093000
2015-03-17 15:52:18.534  - INFO: RoomController - Removing publisher 885464985622093000
2015-03-17 15:52:18.534  - INFO: RoomController - Removed all
2015-03-17 15:52:18.534  - INFO: RoomController - Removing muxer 885464985622093000  muxers left  0
2015-03-17 15:52:18.660  - INFO: ErizoController - Socket disconnect  vBVTSRJ6B_SykBh-RL6W
2015-03-17 15:52:18.661  - INFO: RoomController - Removing subscriptions of  vBVTSRJ6B_SykBh-RL6W
2015-03-17 15:52:18.661  - INFO: ErizoController - Empty room  5508850fa7138ccd5f0bd9c2 . Deleting it
Running process
2015-03-17 15:52:19.267  - INFO: ErizoAgent - Launched new ErizoJS  1f184841-fac4-7ee3-151c-6a1518683b28

/home/pybean/licode/nuve/nuveAPI/rpc/rpc.js:86
    map[corrID].fn('timeout');
                ^
TypeError: Property 'fn' of object #<Object> is not a function
    at callbackError (/home/pybean/licode/nuve/nuveAPI/rpc/rpc.js:86:17)
    at timer._onTimeout (timers.js:219:16)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

**Comment by lodoyun** [comment]
As of f4972e5de15a264700fb374ce38671836cf574fd the Nuve timeout crash is fixed.
I don't really see from the log why erizoController is crashing, are you also deleting the room from Nuve? There might be a race in that case

**Comment by pybean** [comment]
Yes, I was deleting the room from Nuve.

And you are right, I checked my client javascript, and found the race where calling erizo unpublish after nuve room deleting is successful. My bad...

I'm definitely gonna fix the race in my code, but still wonder if you would just warn users 'hey you are trying unpublish/unsubribe from a non-existing room', instead of erizo crash. Such foolproof should make erizo more stable. So please consider.
