### ISSUE TITLE
FIX - mongojs has con method connect

### ISSUE THREAD

**Issue by cadrogui** [ging/licode#304]
Seems to fund a bug in the basic example, cause i recently install licode in a fresh ubuntu 12.4 server and when try to run the example i have a node error like this:

````
/home/music/licode/nuve/nuveAPI/mdb/dataBase.js:28
exports.db = require("mongojs").connect(databaseUrl, collections);
                                ^
TypeError: Object function (connString, cols) {
  var dbname = getDbName(connString);
  var onserver = thunky(function(cb) {
    getTopology(connString, function(err, topology) {
      if (err) return cb(err);
      cb(null, topology);
    });
  });

  if (!dbname) {
    dbname = connString._dbname;
    onserver = thunky(function(cb) {
      toMongodbCore(connString, function(err, server) {
        if (err) cb(new Error('You must pass a connection string or a mongojs instance.'));
        cb(null, server);
      });
    });
  }

  var that = new Database({name: dbname, cols: cols}, onserver);
  if (typeof Proxy !== 'undefined') {
    var p = Proxy.create({
      get: function(obj, prop) {
        if (that[prop]) return that[prop];
        that[prop] = that.collection(prop);
        return that[prop];
      }
    });

    return p;
  };
  return that;
} has no method 'connect'
    at Object.<anonymous> (/home/music/licode/nuve/nuveAPI/mdb/dataBase.js:28:33)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/music/licode/nuve/nuveAPI/nuve.js:5:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
````

to fix the issue you must edit the file 

````
licode/nuve/nuveAPI/mdb/dataBase.js
````

and change like this:

````
// exports.db = require("mongojs").connect(databaseUrl, collections);

var mongojs = require('mongojs');
var db = mongojs('databaseUrl', collections);
````

hope this help others

regards.

**Comment by lodoyun** [comment]
Thanks fixed in 5ebaf9f6018951985fb76e072e8c578c0b1219a0
