### ISSUE TITLE
'setImmediate is not defined' error running basic example with node v0.12.0

### ISSUE THREAD

**Issue by j4y** [ging/licode#308]
I ran into this error running on OSX 10.8.5 and fixed it by downgrading to node v0.10.x

```
$ ./licode/scripts/initBasicExample.sh
...

/Users/jayprall/Code/licode/node_modules/express/lib/router/index.js:188
      setImmediate(done, layerError);
      ^
ReferenceError: setImmediate is not defined
    at next (/Users/jayprall/Code/licode/node_modules/express/lib/router/index.js:188:7)
    at Layer.handle [as handle_request] (/Users/jayprall/Code/licode/node_modules/express/lib/router/layer.js:84:5)
    at trim_prefix (/Users/jayprall/Code/licode/node_modules/express/lib/router/index.js:302:13)
    at proto.handle.c (/Users/jayprall/Code/licode/node_modules/express/lib/router/index.js:270:7)
    at Function.proto.process_params (/Users/jayprall/Code/licode/node_modules/express/lib/router/index.js:321:12)
    at next (/Users/jayprall/Code/licode/node_modules/express/lib/router/index.js:261:10)
    at SendStream.error (/Users/jayprall/Code/licode/node_modules/express/node_modules/serve-static/index.js:107:7)
    at SendStream.EventEmitter.emit (events.js:126:20)
    at SendStream.error (/Users/jayprall/Code/licode/node_modules/express/node_modules/send/index.js:250:17)
    at SendStream.onStatError (/Users/jayprall/Code/licode/node_modules/express/node_modules/send/index.js:346:48)
```

**Comment by zicrox** [comment]
the same thing happens to me in ubuntu 12.04. With node 10.x run fine.

**Comment by mrbatista** [comment]
At the moment licode is not compatibile with Node v0.12

**Comment by nachoaguadoc** [comment]
As @mrbatista says at this moment Licode is not compatible with Node 0.12. For now the last version supported is the one included in the installation scripts.
