### ISSUE TITLE
node erizoAgent.js   spwan error!

### ISSUE THREAD

**Issue by shenyuhit** [ging/licode#324]
when i run  node erizoAgent.js  ,error happend... who can help me?

-------------------------
mqq@10-96-55-199:~/soft/licode/erizo_controller/erizoAgent$ node erizoAgent.js  
begin fill,max = 1|preProcess = 1
erizos.length  = 0|idle_erizos.length = 0
Running process
before spawn..
after spawn..
2015-07-16 10:40:13.164  - INFO: ErizoAgent - Launched new ErizoJS  71e9ea82-a86a-b02b-4a67-c5005928b991
begin fill,max = 1|preProcess = 1
fill out
fill out
sssss
2015-07-16 10:40:13.165  - INFO: AMQPER - begin connect ..
2015-07-16 10:40:13.169  - INFO: AMQPER - create conn succ ..
2015-07-16 10:40:13.169  - INFO: AMQPER - create conn succ 2222..
end

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)

**Comment by prakharsingh** [comment]
I am facing same issue.

> data:    licode/erizo_controller/erizoAgent/erizoAgent.js:4750 - 2016-09-27 14:33:34.874  - INFO: ErizoAgent - Launching a new ErizoJS process
data:    licode/erizo_controller/erizoAgent/erizoAgent.js:4750 - 2016-09-27 14:33:34.877  - INFO: ErizoAgent - Launched new ErizoJS  6de04638-731b-2983-536d-02494bf01693
data:    licode/erizo_controller/erizoAgent/erizoAgent.js:4750 - events.js:72
data:    licode/erizo_controller/erizoAgent/erizoAgent.js:4750 -         throw er; // Unhandled 'error' event
data:    licode/erizo_controller/erizoAgent/erizoAgent.js:4750 -               ^
data:    licode/erizo_controller/erizoAgent/erizoAgent.js:4750 - Error: spawn ENOENT
data:    licode/erizo_controller/erizoAgent/erizoAgent.js:4750 -     at errnoException (child_process.js:1011:11)
data:    licode/erizo_controller/erizoAgent/erizoAgent.js:4750 -     at Process.ChildProcess._handle.onexit (child_process.js:802:34)
data:    licode/erizo_controller/erizoAgent/erizoAgent.js:4750 - error: Forever detected script exited with code: 8
