### ISSUE TITLE
./licode/scripts/initBasicExample.sh error

### ISSUE THREAD

**Issue by john-li-zenith** [ging/licode#346]
error shows below. Any idea?

/home/ubuntu/workspace/licode/extras/basic_example/basicServer.js:37
N.API.init(config.nuve.superserviceID, config.nuve.superserviceKey, 'http://lo
                      ^
TypeError: Cannot read property 'superserviceID' of undefined
    at Object.<anonymous> (/home/ubuntu/workspace/licode/extras/basic_example/basicServer.js:37:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

**Comment by nachoaguadoc** [comment]
Hi,

Have you checked if the parameters in the file licode_config.js are correct? The config.nuve variable should be defined there with all its properties.

**Comment by mkhahani** [comment]
Hi,

Sorry for re-opening the issue. I am getting the same error but the file `licode_config.js` is empty. Re-installing Licode did not help. What should I do?
