### ISSUE TITLE
 Is this a problem of concurrency ?

### ISSUE THREAD

**Issue by leehong** [ging/licode#380]
the error log

createToken() for room 1449557740772695
createToken() for room 1449557740428408
2015-12-08 14:55:40.387  - INFO: RoomsResource - Representing rooms for service  5559463f78645fae6c9c5065
2015-12-08 14:55:40.610  - INFO: RoomsResource - Representing rooms for service  5559463f78645fae6c9c5065
room length 14291
room length 14291
2015-12-08 14:55:41.091  - INFO: RoomsResource - Room created 1449557740772695 (roomName) for service superService , p2p =  false
Created room  56667eec81fe34e116d1f9e3
2015-12-08 14:55:41.485  - INFO: RoomsResource - Room created 1449557740428408 (roomName) for service superService , p2p =  false
Created room  56667eed81fe34e116d1f9e4
2015-12-08 14:55:41.751  - INFO: TokensResource - Room  56667eed81fe34e116d1f9e4  does not exist

/server/licode/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/base.js:246
        throw message;      
              ^
TypeError: Cannot read property '_id' of undefined
    at /server/licode/nuve/nuveAPI/resource/tokensResource.js:176:73
    at /server/licode/nuve/nuveAPI/resource/tokensResource.js:141:17
    at /server/licode/nuve/nuveAPI/mdb/tokenRegistry.js:59:9
    at callback (/server/licode/node_modules/mongojs/index.js:371:7)
    at /server/licode/node_modules/mongojs/node_modules/mongodb/lib/mongodb/collection/core.js:482:9
    at /server/licode/node_modules/mongojs/node_modules/mongodb/lib/mongodb/collection/core.js:128:9
    at /server/licode/node_modules/mongojs/node_modules/mongodb/lib/mongodb/db.js:1195:7
    at /server/licode/node_modules/mongojs/node_modules/mongodb/lib/mongodb/db.js:1903:9
    at Server.Base._callHandler (/server/licode/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at /server/licode/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/server.js:487:18

why the get rooms list the “ Representing rooms for service 5559463f78645fae6c9c5065 ”  twice.

**Comment by lodoyun** [comment]
You are calling createToken twice, that's why you are getting the "Representing rooms" message twice.
Otherwise I would need more information on what you are trying to do... Are you creatingTokens for rooms before creating them?
