### ISSUE TITLE
c++ errors while building erizoAPI after update node

### ISSUE THREAD

**Issue by one-more** [ging/licode#384]
Hi, i am trying to nstallErizo script and got such errors:

In file included from ../OneToManyProcessor.h:9:0,
                 from ../WebRtcConnection.h:7,
                 from ../addon.cc:5:
../ExternalInput.h:16:46: error: expected class-name before ‘{’ token
 class ExternalInput: public node::ObjectWrap {
                                              ^
../ExternalInput.h:29:42: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                          ^
../ExternalInput.h:29:57: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                                         ^
../ExternalInput.h:34:44: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> close(const v8::Arguments& args);
                                            ^
../ExternalInput.h:34:59: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   static v8::Handle<v8::Value> close(const v8::Arguments& args);
... etc

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:88:13)
gyp ERR! stack     at ChildProcess.emit (events.js:173:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:201:12)
gyp ERR! System Linux 3.19.0-39-generic
gyp ERR! command "/usr/local/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /var/www/virt-chat.my/node_server/licode/erizoAPI
gyp ERR! node -v v5.2.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok

**Comment by mrbatista** [comment]
Licode support only node v0.10

**Comment by one-more** [comment]
Do you have plans to support higher versions?

**Comment by fabio-rigato** [comment]
Any news about it?

**Comment by lodoyun** [comment]
We migrated erizoAPI to NAN so you should at least be able to compile erizoAPI. We still ship with node v0.10 atm and can't give you a timeframe for library updates, sorry.
