### ISSUE TITLE
Have issues when I execute installErizo.sh

### ISSUE THREAD

**Issue by changbenny** [ging/licode#395]
I tried to install Licode following the instruments, the console show the error `fatal error: 'boost/thread/mutex.hpp' file not found` when I was running `./licode/scripts/installErizo.sh`.

My environment is mac 10.11.
Is there any suggestions? Thanks.

```
Installing erizoAPI...
building with node-gyp
gyp info it worked if it ends with ok
gyp info using node-gyp@3.2.1
gyp info using node@0.12.5 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/howard/Sites/licode/erizoAPI/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/howard/.node-gyp/0.12.5/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/howard/.node-gyp/0.12.5',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/howard/Sites/licode/erizoAPI',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/addon/addon.o
In file included from ../addon.cc:5:
In file included from ../WebRtcConnection.h:5:
/Users/howard/Sites/./licode/scripts/../erizo/src/erizo/WebRtcConnection.h:6:10: fatal error: 'boost/thread/mutex.hpp' file not found
#include <boost/thread/mutex.hpp>
         ^
1 error generated.
make: *** [Release/obj.target/addon/addon.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/howard/Sites/licode/erizoAPI
gyp ERR! node -v v0.12.5
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
```

**Comment by changbenny** [comment]
I found that cause by other dependency problems.

**Comment by ChukwudiUzoma** [comment]
please, how did you fix it?

**Comment by johnwenjunwu** [comment]
How to fix it? Thanks.
