### ISSUE TITLE
Erizo components seem to crash randomly

### ISSUE THREAD

**Issue by karth295** [ging/licode#400]
TypeError: Cannot read property 'publishers' of undefined
    at Object.that.removePublisher (/home/karthik/licode/erizo_controller/erizoController/roomController.js:345:57)
    at Socket.<anonymous> (/home/karthik/licode/erizo_controller/erizoController/erizoController.js:759:60)
    at Socket.emit (events.js:95:17)
    at Socket.emit (/home/karthik/licode/node_modules/socket.io/lib/socket.js:128:10)
    at Socket.onclose (/home/karthik/licode/node_modules/socket.io/lib/socket.js:425:8)
    at Client.onclose (/home/karthik/licode/node_modules/socket.io/lib/client.js:232:24)
    at Socket.emit (events.js:117:20)
    at Socket.onClose (/home/karthik/licode/node_modules/socket.io/node_modules/engine.io/lib/socket.js:303:10)
    at WebSocket.g (events.js:180:16)
    at WebSocket.emit (events.js:92:17)
2016-01-17 20:56:41.830  - INFO: TokensResource - Created token for room  569b11c318a625ec17bc2373 and service  568a1ab7069cf7655216bf54
2016-01-17 20:56:44.167  - INFO: TokensResource - Created token for room  569b11c318a625ec17bc2373 and service  568a1ab7069cf7655216bf54
2016-01-17 20:56:49.048  - INFO: CloudHandler - ErizoController 1  in  192.241.208.34 does not respond. Deleting it.
2016-01-17 20:56:49.049  - INFO: CloudHandler - [CLOUD HANDLER]: Warning! No erizoController is available.
express deprecated res.send(body, status): Use res.status(status).send(body) instead resource/tokensResource.js:172:21

[_usr_bin_nodejs.0.crash.txt](https://github.com/ging/licode/files/93752/_usr_bin_nodejs.0.crash.txt)

**Comment by karth295** [comment]
Ah, looks like an issue on my end. I will try raising the ulimit.

2016-01-17 20:56:17,326  - DEBUG: WebRtcConnection - Setting VIDEO CANDIDATE
2016-01-17 20:56:17,326  - DEBUG: NiceConnection - Setting remote candidates 0, mediatype 0
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
2016-01-17 20:56:17.327  - INFO: ErizoJSController - Process Signaling message:  468957279808819260 /#r3sWro3JYw5jcRIYAAAo { type: 'candidate',
  candidate: 
   { sdpMLineIndex: 0,
     sdpMid: 'audio',
     candidate: 'a=candidate:379460087 2 tcp 1518217470 2607:fb90:f92:ab65:0:4a:4a78:401 0 typ host tcptype active generation 0' } }
  what():  epoll: Too many open files
./launch.sh: line 5: 23349 Aborted                 (core dumped) node $*

**Comment by karth295** [comment]
Does erizo open a lot more connections than I expect? I only had 10 or 11 people in one room, and then it crashed when the 11th or 12th person tried to join. My ulimit is 1024, and the only extra connection to the server I had was an ssh session. I didn't have any extra open files.

How many connections/files does erizo open per person?

**Comment by karth295** [comment]
I'd like to reopen this issue because it may point to a fd leak of some kind. I'm using licode in a non-standard way. Rather than using Licode's concept of rooms, we have a slightly different, higher level concept of "spaces". So, I use one global, persistent Licode room.

I've seen licode periodically crash, usually days or weeks apart--with tens of people using it in the mean time.

**Comment by lodoyun** [comment]
I've just pushed a fix for a fd leak in ErizoAgent's log files. 
What value did you set up in
```
config.erizoAgent.maxProcesses
```
The fd leak had the side effect of further limiting the amount of sockets each erizoJS (MCU process) could open as fds are inherited from the parent process (ErizoAgent in this case).

In any case you can try updating from the master branch and tell us how it went

**Comment by karth295** [comment]
I didn't set a value for that--I'm not sure what a good value for that would be.

This is a really well architected project, but my only gripe is that it's really poorly documented. It would be nice if there were (detailed) blog posts about how different components work. There are currently a few "god scripts" that abstract away how the system is architected, and that makes it difficult to understand.

It would also be nice to get insights into how to tune/configure licode. For example, can you run licode so that there are ErizoAgents spread across multiple servers?

In the mean time, thanks for the quick fix, I'll try it out and get back to you.
