### ISSUE TITLE
No Erizo Controller available

### ISSUE THREAD

**Issue by theDude30** [ging/licode#447]
The server is not stable, i'm getting the following errors from time to time:

2016-04-17 12:16:44.165  - ERROR: TokensResource - No Erizo Controller available. Error creati
ng token
Error when creating token:  404 ErrorNo Erizo Controller found
2016-04-17 12:16:44.171  - ERROR: TokensResource - No Erizo Controller available. Error creati
ng token
Error when creating token:  404 ErrorNo Erizo Controller found
ESC[0mPOST /createToken/ ESC[0m- ESC[0m- ms - -ESC[0m
ESC[0mPOST /createToken/ ESC[0m- ESC[0m- ms - -ESC[0m
Unhandled connection error: CONNECTION_FORCED - broker forced connection closure with reason '
shutdown'
2016-04-18 05:25:19.042  - ERROR: AMQPER - Connection error... { [Error: CONNECTION_FORCED - b
roker forced connection closure with reason 'shutdown'] code: 320 }
Error: CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'
    at Connection._onMethod (/opt/licode/node_modules/amqp/lib/connection.js:508:15)
    at AMQPParser.self.parser.onMethod (/opt/licode/node_modules/amqp/lib/connection.js:136:12
)
    at AMQPParser._parseMethodFrame (/opt/licode/node_modules/amqp/lib/parser.js:363:10)
    at frameEnd (/opt/licode/node_modules/amqp/lib/parser.js:93:16)
    at frame (/opt/licode/node_modules/amqp/lib/parser.js:78:14)
    at AMQPParser.header [as parse] (/opt/licode/node_modules/amqp/lib/parser.js:64:14)
    at AMQPParser.execute (/opt/licode/node_modules/amqp/lib/parser.js:137:21)
    at Connection.<anonymous> (/opt/licode/node_modules/amqp/lib/connection.js:174:21)
    at Connection.emit (events.js:95:17)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)  killing process.
Unhandled connection error: CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'
2016-04-18 05:25:19.051  - ERROR: RPC - Connection error... { [Error: CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'] code: 320 }
Error: CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'
    at Connection._onMethod (/opt/licode/node_modules/amqp/lib/connection.js:508:15)
    at AMQPParser.self.parser.onMethod (/opt/licode/node_modules/amqp/lib/connection.js:136:12)
    at AMQPParser._parseMethodFrame (/opt/licode/node_modules/amqp/lib/parser.js:363:10)
    at frameEnd (/opt/licode/node_modules/amqp/lib/parser.js:93:16)
    at frame (/opt/licode/node_modules/amqp/lib/parser.js:78:14)
    at AMQPParser.header [as parse] (/opt/licode/node_modules/amqp/lib/parser.js:64:14)
    at AMQPParser.execute (/opt/licode/node_modules/amqp/lib/parser.js:137:21)
    at Connection.<anonymous> (/opt/licode/node_modules/amqp/lib/connection.js:174:21)
    at Connection.emit (events.js:95:17)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)  killing process.
Unhandled connection error: CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'
2016-04-18 05:25:19.051  - ERROR: RPC - Connection error... { [Error: CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'] code: 320 }
Error: CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'
    at Connection._onMethod (/opt/licode/node_modules/amqp/lib/connection.js:508:15)
    at AMQPParser.self.parser.onMethod (/opt/licode/node_modules/amqp/lib/connection.js:136:12)
    at AMQPParser._parseMethodFrame (/opt/licode/node_modules/amqp/lib/parser.js:363:10)
    at frameEnd (/opt/licode/node_modules/amqp/lib/parser.js:93:16)
    at frame (/opt/licode/node_modules/amqp/lib/parser.js:78:14)
    at AMQPParser.header [as parse] (/opt/licode/node_modules/amqp/lib/parser.js:64:14)
    at AMQPParser.execute (/opt/licode/node_modules/amqp/lib/parser.js:137:21)
    at Connection.<anonymous> (/opt/licode/node_modules/amqp/lib/connection.js:174:21)
    at Connection.emit (events.js:95:17)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)  killing process.

**Comment by lodoyun** [comment]
Looks like the components of Licode are having problems connecting to rabbitmq. Is it installed in the same host?

**Comment by theDude30** [comment]
it is installed on the same server, and it works for few times(around 10 times) and then i'm getting the above error.

**Comment by prakharsingh** [comment]
I have the same error:
`2016-10-15 15:11:29.159  - ERROR: CloudHandler - No erizoController is available.
2016-10-15 15:12:08.956  - ERROR: TokensResource - No Erizo Controller available. Error creating token
2016-10-15 15:12:26.960  - ERROR: TokensResource - No Erizo Controller available. Error creating token
2016-10-15 15:12:34.965  - ERROR: TokensResource - No Erizo Controller available. Error creating token
2016-10-15 15:13:55.597  - ERROR: TokensResource - No Erizo Controller available. Error creating token
2016-10-15 15:14:09.345  - ERROR: TokensResource - No Erizo Controller available. Error creating token
2016-10-15 15:14:23.574  - ERROR: TokensResource - No Erizo Controller available. Error creating token
2016-10-15 15:14:37.798  - ERROR: TokensResource - No Erizo Controller available. Error creating token
2016-10-15 15:14:54.057  - ERROR: TokensResource - No Erizo Controller available. Error creating token
2016-10-15 15:15:07.264  - ERROR: TokensResource - No Erizo Controller available. Error creating token
2016-10-15 15:15:23.202  - ERROR: TokensResource - No Erizo Controller available. Error creating token
2016-10-15 15:15:37.454  - ERROR: TokensResource - No Erizo Controller available. Error creating token
2016-10-15 15:15:51.705  - ERROR: TokensResource - No Erizo Controller available. Error creating token
2016-10-15 15:16:05.960  - ERROR: TokensResource - No Erizo Controller available. Error creating token
2016-10-15 15:16:20.216  - ERROR: TokensResource - No Erizo Controller available. Error creating token
2016-10-15 15:16:35.024  - ERROR: TokensResource - No Erizo Controller available. Error creating token
2016-10-15 15:16:49.248  - ERROR: TokensResource - No Erizo Controller available. Error creating token
2016-10-15 15:17:03.459  - ERROR: TokensResource - No Erizo Controller available. Error creating token
2016-10-15 15:17:17.728  - ERROR: TokensResource - No Erizo Controller available. Error creating token
`

**Comment by evilword666** [comment]
I have the same problem :(
Note:  rabbitmq is installed in the same host

_2018-10-04 20:13:36.194  - ERROR: CloudHandler - No erizoController is available.
2018-10-04 20:13:47.209  - ERROR: TokensResource - message: createToken error, errorMgs: No Erizo Controller available
Error creating token 404 ErrorNo Erizo Controller found
POST /createToken/ 401 11038.980 ms - 25_

**Comment by WalterWee** [comment]
still get this error now

**Comment by riebling** [comment]
I am also getting part of the same error, and would love to know what is really the problem; what is the code trying to do - what exactly fails just before printing:
```
2020-05-13 09:51:52.518  - ERROR: TokensResource - message: createToken error, errorMgs: No Erizo Controller available
Error creating token 404 ErrorNo Erizo Controller found
POST /createToken/ 401 529.295 ms - 25
```

**Comment by harikt** [comment]
The docker image provided by yours works fine ( Not saying I was able to run the test connection ) . But I wanted to make some changes and buid a new image. So these are what I did and what error it cause.

```
sudo docker build -t licode-image .
```

Without changes also the build was throwing error 

```
Starting Nuve
2020-10-29 16:13:12.883  - ERROR: RPC - message: AMQP connection error killing process, errorMsg: errno: ECONNREFUSED, code: ECONNREFUSED, syscall: connect, address: 127.0.0.1, port: 5672
Starting erizoController
Starting erizoAgent
Starting basicExample
2020-10-29 16:13:17.687  - INFO: ErizoAgent - message: launched new ErizoJS, erizoId: 61a7fa06-4e3f-7c4f-1584-93ba2a9f2188
[erizo-61a7fa06-4e3f-7c4f-1584-93ba2a9f2188] 2020-10-29 16:13:18.003  - INFO: ErizoJS - Starting ioThreadPool
[erizo-61a7fa06-4e3f-7c4f-1584-93ba2a9f2188] 2020-10-29 16:13:18.050  - INFO: ErizoJS - message: Started, erizoId: 61a7fa06-4e3f-7c4f-1584-93ba2a9f2188, isDebugMode: false
2020-10-29 16:13:22.823  - WARN: ErizoController - message: addECToCloudHandler cloudHandler does not respond, attemptsLeft: 5
2020-10-29 16:13:30.829  - WARN: ErizoController - message: addECToCloudHandler cloudHandler does not respond, attemptsLeft: 4
2020-10-29 16:13:38.832  - WARN: ErizoController - message: addECToCloudHandler cloudHandler does not respond, attemptsLeft: 3

2020-10-29 16:13:46.837  - WARN: ErizoController - message: addECToCloudHandler cloudHandler does not respond, attemptsLeft: 2

2020-10-29 16:13:54.843  - WARN: ErizoController - message: addECToCloudHandler cloudHandler does not respond, attemptsLeft: 1
2020-10-29 16:13:57.845  - ERROR: ErizoController - message: addECtoCloudHandler cloudHandler does not respond - fatal
```

Using the latest commit `0f781ce2177d347a25c6e8768a9190c64aad46f6` .

Note : The reason I was trying to create the build was to make change in `licode_config.js` . 

```
// This configuration is used by the clients to reach erizoController
// Use '' to use the public IP address instead of a hostname
config.erizoController.hostname = 'nlicode.buildful.com'; //default value: ''
config.erizoController.port = 443; //default value: 8080
// Use true if clients communicate with erizoController over SSL
config.erizoController.ssl = true; //default value: false
```

I don't find an easy way to change the config and start the docker container. Evern if we change file in container stopping and starting container will over write. I am new to docker, so wondering it would have been good if we can pass an ENV value to the port and ssl would be good.
