### ISSUE TITLE
Cannot start basic example webserver

### ISSUE THREAD

**Issue by pybean** [ging/licode#468]
I tried to launch the basic example server in licode server, and got the error shown as below. I installed errorhandler npm module but still gets the same error.
<pre>
$ ./licode/scripts/initBasicExample.sh 
module.js:340
    throw err;
          ^
Error: Cannot find module 'errorhandler'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/zignage/licode/extras/basic_example/basicServer.js:4:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
</pre>

**Comment by ytjjyy** [comment]
`rm -rf  /path/licode `
Plaese try a agian resintall

**Comment by pybean** [comment]
Sorry, deleting and rebuilding everything just for a single problem doesn't seem to be a good approach for debugging. Other components like nuve, erizocontroller and erizoagent are still running properly. But, I do clean and recompile 'build' directories every time I update the licode server.

**Comment by pybean** [comment]
Nevermind, I missed the step "installBasicExample.sh" before launching the basic server so it couldn't find required modules.
