### ISSUE TITLE
Can't run ErizoAgent through forever

### ISSUE THREAD

**Issue by prakharsingh** [ging/licode#531]
> data:    licode/erizo_controller/erizoAgent/erizoAgent.js:8634 - 2016-09-27 15:31:53.642  - INFO: ErizoAgent - Launching a new ErizoJS process
data:    licode/erizo_controller/erizoAgent/erizoAgent.js:8634 - 2016-09-27 15:31:53.645  - INFO: ErizoAgent - Launched new ErizoJS  6f237f1a-8b65-1e7c-d07c-b1a97f198c1b
data:    licode/erizo_controller/erizoAgent/erizoAgent.js:8634 - events.js:72
data:    licode/erizo_controller/erizoAgent/erizoAgent.js:8634 -         throw er; // Unhandled 'error' event
data:    licode/erizo_controller/erizoAgent/erizoAgent.js:8634 -               ^
data:    licode/erizo_controller/erizoAgent/erizoAgent.js:8634 - Error: spawn ENOENT
data:    licode/erizo_controller/erizoAgent/erizoAgent.js:8634 -     at errnoException (child_process.js:1011:11)
data:    licode/erizo_controller/erizoAgent/erizoAgent.js:8634 -     at Process.ChildProcess._handle.onexit (child_process.js:802:34)
data:    licode/erizo_controller/erizoAgent/erizoAgent.js:8634 - error: Forever detected script exited with code: 8

**Comment by jcague** [comment]
ErizoAgent launches ErizoJS internally, seems like it's failing. Please check that the working directory doesn't change.
